version: '3.3'
services:
    mguplon:
        build:
            './.docker'
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/opt/www/MGUplon
        network_mode: host
