version: '3.3'
services:
    mguplon:
        build:
            './.docker'
        working_dir: /opt/www/MGUplon
        tty: true
        command: > 
            bash -c "chmod -R a+w /opt/www/MGUplon/storage
            && chmod -R a+w /opt/www/MGUplon/bootstrap 
            && cd /opt/www/MGUplon 
            && service nginx start 
            && service php7.1-fpm start 
            && composer install 
            && /bin/bash"
        volumes:
            - ./:/opt/www/MGUplon
        network_mode: host
